# Pipeline configuration

# --- Organsim to restrict search to
organism: "Trichostrongylidae"

# ---- Marker gene to search.  Currently ITS2 and 18S are supported
marker: "18S"

# --- Output directory
out_directory: "Trichostrongylidae_18S"

# --- Marker specific paramters

ITS2:
  max_width: 700
  min_width: 100

18S:
  max_width: 1500
  min_width: 100

return_untrimmed: TRUE

# --- General
ncbi_api: "d4298b86aa9b9f94d974ea48d1152cc60e08"
threads: 4 




